const initialState={
    newOrder:null,
    users:[],
    warehouse:[],
    assets:[],
    orders:[],
    order:null
}

export default function AssetReducer(state=initialState,action){
    if(action.type==='order/save'){
        return({
            ...state,
            newOrder:action.payload
        })
    }
    if(action.type==='user/all'){
        return({
            ...state,
            users:action.payload
        })
    }
    if(action.type=='warehouse/all'){
        return({
            ...state,
            warehouse:action.payload
        })
    }
    if(action.type=='asset/all'){
        return({
            ...state,
            assets:action.payload
        })
    }
    if(action.type=='order/all'){
        return({
            ...state,
            orders:action.payload
        })
    }
    if(action.type=='order/byId'){
        return({
            ...state,
            order:action.payload
        })
    }
    else{
        return state;
    }
}